add projects, about me sections
mj-e-boc/Ronald-Portfolio pull request #2
Opened 2023-01-13 18:47 UTC by mj-e-boc

-Add projects section
-Add about me section

2023-01-13 19:07 UTC, Shedrack-Sunday requested changes
Hi @mj-e-boc , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Invalid Code Review Request 🔧 

You have submitted a project, that has some issues with the README file.
- Make sure all links lead to a path, like the LICENSE, and remove all the section line with a `>` sign. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-01-14 13:29 UTC, NahnahAJ requested changes
Hi <STUDENT_MENTION>, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media3.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

## Highlights


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 13:29 UTC, NahnahAJ commented on styles.css
> +}
- [ ] Please ensure that `display: grid ` is used in your works section. I noticed that the name you gave to your section class is different from what you styled. Please fix this so that your works section can be properly styled :100: 
![image](https://user-images.githubusercontent.com/102699958/212472769-4da244cf-fe1f-417f-bf53-7058c4a5e61d.png)

2023-01-14 13:29 UTC, NahnahAJ commented on index.html
> +    </button>
- [ ] This button looks slightly different from the one in the Figma design. Please try to stick to the design as much as possible. So please refer to the images below and fix this as well :100: 
- [ ] Kindly repeat this process for all the other buttons in your project. including the `Get my resume` button :100: 
- Your Design
![image](https://user-images.githubusercontent.com/102699958/212473124-298e2c94-f80a-4902-b2b9-efafc3361397.png)

- The Figma Design
![image](https://user-images.githubusercontent.com/102699958/212473147-f98b0851-20c5-4beb-9792-ebd02d4ca9ce.png)

2023-01-14 13:29 UTC, NahnahAJ commented on index.html
> +    <p>
- [ ] Please wrap the entire ABOUT ME section in a (`section` tag) instead of this div. This is because the section element can be used to divide up a web page into standalone sections of related content. You can read more about why this is necessary [here](https://www.w3schools.com/tags/tag_section.asp) :wink:

2023-01-14 13:29 UTC, NahnahAJ commented on index.html
- Please remove this `div` block from your project as it is of no relevance here. :100:

2023-01-14 13:29 UTC, NahnahAJ commented on index.html
>      </ul>
- [ ] I noticed that this part of your project wasn't well arranged. In the Figma design, this is how it looks
![image](https://user-images.githubusercontent.com/102699958/212473909-76e85045-4bea-44f8-9197-39aeb26499de.png)
But this is how it looks in your project
![image](https://user-images.githubusercontent.com/102699958/212474064-10a3f6d0-13f2-46a3-87c5-53b934941d07.png)

 so kindly do well to fix these as well :+1: and reduced the spacing between elements so your design looks like an exact replica of the Figma design :100:

2023-01-14 15:01 UTC, christianbiring1 approved these changes
Hi @mj-e-boc , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 
![APPROVED](https://user-images.githubusercontent.com/97100091/212478440-f95413f4-2531-45dd-8314-6f2c2b6d682b.gif)

## Highlights
- [ ] All lines checks are green :heavy_check_mark: 
- [ ] Descriptive PR `title` and `summary`
## Optional suggestions
- [ ] `Kindly make sure the Poppins font is used correctly.`
`Hint: Since it's not a default browser font, you will need to import it from google fonts and then use it in your project.` :smile: 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 15:28 UTC, merged