Desktopview
mj-e-boc/Ronald-Portfolio pull request #4
Opened 2023-01-19 22:08 UTC by mj-e-boc

-Add index.html, styles.css for desktop view

2023-01-19 22:31 UTC, vickymarz requested changes
Hi @mj-e-boc , 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅  
- The README is well documented ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️

- [ ] KIndly reduce the font size of all your list of technologies to match the figma design. KIndly check the figma design property values 💯 

FIgma design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/213576124-00af1e88-677b-4ee3-aaef-bfd82121b639.png)

Your design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/213576067-baac9c0c-80aa-4430-9e87-2c22bcbb992b.png)

- [ ] Kindly use the appropriate background color for the projects card and about me button as it is on the figma design  👍🏽 

Your design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/213576578-353d668a-8c76-4e25-bd63-2208186e2b71.png)

FIgma design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/213576685-32c575f1-bc2a-4af3-aabd-08a7e5c418e8.png)



_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 22:31 UTC, vickymarz commented on index.html
> -             </ul>
- [ ] Good job aligning the content of your headline section the left. 👍🏽 . KIndly make sure that the entire content is at the center of the page to match the figma design.'

Figma design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/213574456-1494661e-af06-438b-a57a-b4b942ab2625.png)

Your design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/213574607-ed96f709-d02c-4e25-a46f-ccc0625829d3.png)

2023-01-19 22:31 UTC, vickymarz commented on index.html
> +        </ul>
- [ ] KIndly reduce the spacing between the social icons to match the figma design 👍🏽 

FIgma design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/213574793-c99085ac-e23a-42cd-bafe-581cb2bef1f6.png)

Your design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/213575071-7b55183b-59c7-4c6d-979d-92d6388607e7.png)

2023-01-19 22:31 UTC, vickymarz commented on index.html
> +    <section class="projectscards">
- [ ] KIndly reduce the spacing between your headline section and the projects section to match the figma design 👍🏽 

Figma design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/213575315-fc7a2bd6-144f-41fb-84e3-c26b948c93fc.png)

Your design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/213575429-18e4cf41-c811-4e30-add2-c0c3d566c78c.png)

2023-01-19 22:31 UTC, vickymarz commented on index.html
> +          </ul>
- [ ] KIndly reduce the font size of all your list of technologies to match the figma design. KIndly check the figma design property values 💯 

FIgma design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/213576124-00af1e88-677b-4ee3-aaef-bfd82121b639.png)

Your design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/213576067-baac9c0c-80aa-4430-9e87-2c22bcbb992b.png)

2023-01-19 22:31 UTC, vickymarz commented on index.html
> +          <button type="button" class="button">See Project</button>
- [ ] KIndly use the appropriate background color for the button as it is on the figma design  👍🏽 

YOur design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/213576578-353d668a-8c76-4e25-bd63-2208186e2b71.png)

FIgma design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/213576685-32c575f1-bc2a-4af3-aabd-08a7e5c418e8.png)

2023-01-20 00:01 UTC, wayungi requested changes
Hi @mj-e-boc , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![image](https://user-images.githubusercontent.com/99656687/213588477-e1b7d95c-044a-4b76-8b7d-6be6af89036c.png)


 ## Highlights
 - Great work using the right GitHub Flow 💯 
 - Linters are passing 👍🏾 
 - Project Documentation (PR, README) is professional 👏🏾 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 01:39 UTC, AlphaNtihinduka approved these changes
# STATUS: APPROVED :green_circle: :clap: 
## Hi @mj-e-boc     🙋‍♂️, 

Your project is complete!  There is nothing else to say other than... Great job 👏 

![approved-accepted](https://user-images.githubusercontent.com/99394374/212473432-e725752b-8682-4dbb-993e-9e466dbe7acb.gif)

Congratulations! 🎉 
TO HIGHLIGHT:

- Your project is professional :heavy_check_mark: 
- Your repo is professional :heavy_check_mark: 
- Well-structured files :heavy_check_mark: 
- Professional README.md file 💯
- No linter errors :heavy_check_mark: 

Now you can merge this branch and move on :1st_place_medal: 


## Optional suggestions
- Kindly refer to the inline optional suggestions made. Ensure to apply them to have a professional project that suits recruiters' needs.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :four_leaf_clover:

2023-01-20 01:39 UTC, AlphaNtihinduka commented on styles.css
> +  }
- [ ] [OPTIONAL] I have noticed that your `.abtme` has a `padding: 20% 5%`. This causes high spacing which does not stick to the [Figma design template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=NUG5R401LrO7ZCOa-0) :no_good: Please, consider reducing the padding top and bottom of the section. 
- Figma design :sunglasses: 
![Screenshot from 2023-01-20 04-34-32](https://user-images.githubusercontent.com/99394374/213599339-3cd5316a-ca4a-4a91-a9b9-584202ee1dca.png)

- Your design :sunglasses: 
![Screenshot from 2023-01-20 04-35-55](https://user-images.githubusercontent.com/99394374/213599350-1a30ea69-1704-4ac9-8434-330ec255107c.png)

2023-01-20 07:17 UTC, alexiscyber14 commented on styles.css
> +.textitems{}
Please try to not keep empty blocks of Code. This will help your code be more organized.

2023-01-20 07:20 UTC, alexiscyber14 commented on styles.css
>    .pro2 button {
Please try and remove this empty block of code as well. from line 327-417

2023-01-20 07:41 UTC, merged